#!/bin/bash

clock=$(date '+%I')

case "$clock" in
"00") icon="󱑖" ;;
"01") icon="󱑋" ;;
"02") icon="󱑌" ;;
"03") icon="󱑍" ;;
"04") icon="󱑎" ;;
"05") icon="󱑏" ;;
"06") icon="󱑐" ;;
"07") icon="󱑑" ;;
"08") icon="󱑒" ;;
"09") icon="󱑓" ;;
"10") icon="󱑔" ;;
"11") icon="󱑕" ;;
"12") icon="󱑖" ;;
esac

case $BLOCK_BUTTON in
3) setsid -f st -e sh -c 'cal; exec zsh' ;;
esac

str=$(date +"󰸘 %A, %B %d %Y $icon %H:%M")

echo "$str "
